# 🎨 Theme
[general]
import = ["~/.config/alacritty/themes/Arcoiris.toml"]
live_config_reload = true

# 🔤 Font settings
[font]
builtin_box_drawing = true
size = 11.5

[font.normal]
family = "Maple Mono NF CN"
style = "Regular"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

# ➕ Terminal environment
[env]
TERM = "alacritty"

# 🖱 Mouse behavior
[mouse]
hide_when_typing = true

# 🖋 Cursor style
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Beam"

# 📜 Scrolling
[scrolling]
history = 100000
multiplier = 6

# 🔍 Text selection
[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# 🖥️ Window behavior
[window]
dynamic_title = true
opacity = 0.9
title = "Alacritty"
decorations = "None"

[window.class]
general = "Alacritty"
instance = "Alacritty"

# 🌈 Color options
[colors]
draw_bold_text_with_bright_colors = true

# 🔗 URL hints
[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
post_processing = true
persist = false
regex = "(https?://[^\"]+)"

# ⌨️ Keybindings
[[keyboard.bindings]]
action = "Paste"
key = "Y"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "W"
mods = "Alt"

# 🐚 Default shell
[terminal.shell]
program = "/bin/fish"
